server:
  port: 8082

spring:
  application:
    name: ique-sms
  security:
    oauth2:
      resource-server:
        jwt:
          jws-algorithm: RS256
          public-key-location: file:./jwt_key.pub
  datasource:
    url: jdbc:postgresql://localhost:5432/iqueue
    username: ${DB_USER:user1}
    password: ${DB_PASS:pass1}
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redis}

feign:
  server:
    name: ique-qms
  client:
    url:
      qms: ${QMS_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
