server:
  port: 8082

spring:
  application:
    name: ique-sms
  cloud:
    gcp:
      sql:
        instance-connection-name: ique-star6ucks:asia-southeast1:iqueue
        database-name: ique
  kubernetes:
    discovery:
      all-namespaces=true: true
  datasource:
    #    url: jdbc:postgresql://localhost:5432/iqueue
    #    url: jdbc:postgresql:///ique
    url: jdbc:postgresql://ique
    username: ${DB_USER:ums}
    password: ${DB_PASS:&2ZxqMQF'2{fQT}b}
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
