server:
  port: 8082

spring:
  application:
    name: ique-sms
  cloud:
    gcp:
      project-id: ique-star6ucks
      sql:
        instance-connection-name: ique-star6ucks:asia-southeast1:iqueue
        database-name: ique
      credentials:
        location: file:/secrets/credentials.json
  #  kubernetes:
  #    discovery:
  #      all-namespaces=true: true
  datasource:
    #    url: jdbc:postgresql://localhost:5432/iqueue
    #    url: jdbc:postgresql:///ique
    url: jdbc:postgresql://ique
    username: ${DB_USER}
    password: ${DB_PASS}
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    show-sql: true

feign:
  client:
    url:
      qms: ${QMS_URL:http://10.24.7.94}
#      qms: ${QMS_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
